inherit_from: .rubocop_todo.yml

require: rubocop-rails
AllCops:
    Exclude:
      - 'db/**/*'
      - 'config/**/*'
      - 'script/**/*'
      - 'bin/{rails,rake}'
      - !ruby/regexp /old_and_unused\.rb$/